### PR TITLE
Workaround for __name__ grouping in avg()

### LINKED ISSUE #274: Metric names not preserved in query
Hello! I'm running into an issue where it seems that the metric name is not being preserved, and it leads to duplication errors.

Setup:

- Two identically configured v2.15.2 prometheus servers for HA running in k8s installed by the community helm chart promtheus-operator

- One v0.0.57 promxy running in a pod with the following configuration:

```
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 30s
      external_labels:
        source: promxy
    remote_write:
    promxy:
      server_groups:
        - static_configs:
            - targets:
              - prom-server-0
              - prom-server-1
          labels:
            server_group: group_1
          anti_affinity: 30s
          remote_read: true
          remote_read_path: api/v1/read
          path_prefix:
          query_params:
            nocache: 1
          http_client:
            dial_timeout: 10s
            tls_config:
              insecure_skip_verify: false
          relative_time_range:
            start:
            end:
          absolute_time_range:
            start:
            end:
          ignore_error: true
```
Query Specifics:
We have 4 metrics with different values:

- metric_1 
- metric_10
- metric_1000
- metric_10000

This query returns an error:

```
avg ({__name__=~"metric_.*"}) by (__name__)

Error executing query: found duplicate series for the match group {__name__="metric_10"} on the right hand-side of the operation: [{__name__="metric_10"}, {__name__="metric_1"}];many-to-many matching not allowed: matching labels must be unique on one side
```

On our prometheus servers however, the metric names are preserved and yield 4 different time series such as:

- metric_1{} = 1
- metric_10{} = 10
- metric_1000{} = 1000
- metric_10000{} = 10000

here are some logs from that query:

```
time="2020-02-26T19:58:08Z" level=debug msg="AggregateExpr avg by(__name__) ({__name__=~\"metric_.*\"}) avg"
time="2020-02-26T19:58:08Z" level=debug msg="AggregateExpr count by(__name__) ({__name__=~\"metric_.*\"}) count"
time="2020-02-26T19:58:08Z" level=debug msg="http://prom-server-1" api=Query query="count by(__name__) ({__name__=~\"metric_.*\"})" ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:08Z" level=debug msg="AggregateExpr sum by(__name__) ({__name__=~\"metric_.*\"}) sum"
time="2020-02-26T19:58:08Z" level=debug msg="http://prom-server-0" api=Query query="count by(__name__) ({__name__=~\"metric_.*\"})" ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:08Z" level=debug msg="http://prom-server-1" api=Query query="sum by(__name__) ({__name__=~\"metric_.*\"})" ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:08Z" level=debug msg="http://prom-server-0" api=Query query="sum by(__name__) ({__name__=~\"metric_.*\"})" ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:09Z" level=debug msg="http://prom-server-0" api=Query query="sum by(__name__) ({__name__=~\"metric_.*\"})" took=92.94947ms ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:09Z" level=debug msg="http://prom-server-0" api=Query query="count by(__name__) ({__name__=~\"metric_.*\"})" took=95.979287ms ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:09Z" level=debug msg="http://prom-server-1" api=Query query="count by(__name__) ({__name__=~\"metric_.*\"})" took=104.073632ms ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:09Z" level=debug msg="http://prom-server-1" api=Query query="sum by(__name__) ({__name__=~\"metric_.*\"})" took=105.678827ms ts="2020-02-26 19:58:08.818 +0000 UTC"
100.97.247.189 - - [26/Feb/2020 19:58:09] "GET /api/v1/query HTTP/1.1 422 233" 0.107625 query=avg+%28%7B__name__%3D~%22metric_.%2A%22%7D%29+by+%28__name__%29&time=1582747088.818&_=1582739994726
```

I also tested this setup with v2.13.0 of prometheus, but got the same error. Please let me know if you need more information.

### PR DESCRIPTION
**Pull request by jacksontj**
Right now promql's BinaryExpr strips the __name__ label -- which breaks
the avg() optimizations in the NodeReplacer. This patch implements a
relabel workaround (which is nasty, but works) to relabel `__name__` ->
`__name` and then back.

Fixes #274

Special thanks to @john-delivuk for the debugging help!

TODO:
- [x] Investigate mechanism without string() and parse

### CODE REVIEW

File: pkg/proxystorage/util.go [hunk 1]
```diff
@@ -115,3 +115,9 @@ func CloneExpr(expr promql.Expr) (newExpr promql.Expr) {
 	newExpr, _ = promql.ParseExpr(expr.String())
 	return
 }
+
+// PreserveLabel wraps the input expression with a label replace in order to preserve the metadata through binary expressions
+func PreserveLabel(expr promql.Expr, srcLabel string, dstLabel string) (relabelExpress promql.Expr) {
```
Comment (jacksontj) [inline pkg/proxystorage/util.go]: I'd like to find a way to create this object without having to string and unstring everything if possible (this works, just feels nasty)

Comment (jacksontj) [reply pkg/proxystorage/util.go]: I've looked a bit into this and the promql package doesn't make this easy. I also ran a benchmark and it seems that the perf hit is non-existant:

```
benchmark                                                               old ns/op     new ns/op     delta
BenchmarkEvaluations/benchdata/aggregators.test/direct-4                20803         20102         -3.37%
BenchmarkEvaluations/benchdata/aggregators.test/promxy-4                232304        226409        -2.54%
BenchmarkEvaluations/benchdata/aggregators.test/promxy_remoteread-4     233642        231085        -1.09%

benchmark                                                               old allocs     new allocs     delta
BenchmarkEvaluations/benchdata/aggregators.test/direct-4                143            143            +0.00%
BenchmarkEvaluations/benchdata/aggregators.test/promxy-4                572            571            -0.17%
BenchmarkEvaluations/benchdata/aggregators.test/promxy_remoteread-4     569            569            +0.00%

benchmark                                                               old bytes     new bytes     delta
BenchmarkEvaluations/benchdata/aggregators.test/direct-4                7517          7517          +0.00%
BenchmarkEvaluations/benchdata/aggregators.test/promxy-4                37130         36696         -1.17%
BenchmarkEvaluations/benchdata/aggregators.test/promxy_remoteread-4     36737         36776         +0.11%

```

So assuming tests pass, I'll rebase/squash and we should be good to go.

Comment (john-delivuk) [reply pkg/proxystorage/util.go]: I'm new to these libraries so I'll continue to dig for a better option. I'm not sure if there is a better way to run the `label_replace` function as it **has** to be outside of the aggregate and **not** inside.

Comment (jacksontj) [reply pkg/proxystorage/util.go]: Besides the fact that this is ugly (String-ing and re-parsing) this seems fine; I was worried that the re-parse would be dramatically slower, but it seems its not noticeable in the scheme of things :)
